server:
  port: 7002
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7003.com:7003/eureka
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: eureka-7002.com
spring:
  application:
    name: eureka-7002.com