server:
  port: 7002
eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka-7001.com:7001/eureka,http://eureka-7003.com:7003/eureka
    register-with-eureka: false    # 当前的微服务不注册到eureka之中
    fetch-registry: false     # 不通过eureka获取注册信息
  instance:
    hostname: eureka-7002.com
spring:
  application:
    name: eureka-7002.com